apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "kapel.fullname" . }}-processor-config
  labels:
    {{- include "kapel.labels" . | nindent 4 }}
data:
{{ .Values.processor.config | indent 2 }}
