apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ssmsend-secret
  labels:
    {{- include "kapel.labels" . | nindent 4 }}
type: Opaque
data:
  hostcert.pem: {{ .Values.ssmsend.hostcert }}
  hostkey.pem: {{ .Values.ssmsend.hostkey }}
