apiVersion: v1
kind: Secret
metadata:
  name: {{ template "kapel.fullname" . }}-ssmsend-secret
  labels:
    {{- include "kapel.labels" . | nindent 4 }}
type: Opaque
stringData:
  hostcert.pem: {{ toYaml .Values.ssmsend.hostcert | indent 4 }}
  hostkey.pem: {{ toYaml .Values.ssmsend.hostkey | indent 4 }}
