apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ssmsend-secret
  labels:
    {{- include "kapel.labels" . | nindent 4 }}
type: Opaque
data:
  x509cert.pem: {{ .Values.ssmsend.x509cert }}
  x509key.pem: {{ .Values.ssmsend.x509key }}
